Controllers/THangsController.cs
/*using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Models;

namespace Admin.Controllers
{
    public class THangsController : Controller
    {
        private readonly QLBanDTContext _context;

        public THangsController(QLBanDTContext context)
        {
            _context = context;
        }

        // GET: THangs
        public async Task<IActionResult> Index()
        {
              return _context.TKhachHangs != null ? 
                          View(await _context.TKhachHangs.ToListAsync()) :
                          Problem("Entity set 'QLBanDTContext.TKhachHangs'  is null.");
        }

        // GET: THangs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.TKhachHangs == null)
            {
                return NotFound();
            }

            var tKhachHang = await _context.TKhachHangs
                .FirstOrDefaultAsync(m => m.MaKh == id);
            if (tKhachHang == null)
            {
                return NotFound();
            }

            return View(tKhachHang);
        }

        // GET: THangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: THangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKh,TenKh,GioiTinh,DiaChi,DienThoai,Email")]  tKhachHang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tKhachHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tKhachHang);
        }

        // GET: THangs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.TKhachHangs == null)
            {
                return NotFound();
            }

            var tKhachHang = await _context.TKhachHangs.FindAsync(id);
            if (tKhachHang == null)
            {
                return NotFound();
            }
            return View(tKhachHang);
        }

        // POST: THangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaKh,TenKh,GioiTinh,DiaChi,DienThoai,Email")] TKhachHang tKhachHang)
        {
            if (id != tKhachHang.MaKh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tKhachHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TKhachHangExists(tKhachHang.MaKh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tKhachHang);
        }

        // GET: THangs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.TKhachHangs == null)
            {
                return NotFound();
            }

            var tKhachHang = await _context.TKhachHangs
                .FirstOrDefaultAsync(m => m.MaKh == id);
            if (tKhachHang == null)
            {
                return NotFound();
            }

            return View(tKhachHang);
        }

        // POST: THangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.TKhachHangs == null)
            {
                return Problem("Entity set 'QLBanDTContext.TKhachHangs'  is null.");
            }
            var tKhachHang = await _context.TKhachHangs.FindAsync(id);
            if (tKhachHang != null)
            {
                _context.TKhachHangs.Remove(tKhachHang);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TKhachHangExists(string id)
        {
          return (_context.TKhachHangs?.Any(e => e.MaKh == id)).GetValueOrDefault();
        }
    }
}
*/

Controllers/TSpsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Models;
using Admin.Services;
using PagedList;
using Admin.Models.ViewModels;
using System.Xml.Linq;
using Admin.InputModels;

namespace Admin.Controllers
{
    public class TSpsController : Controller
    {
        private readonly QLBanDTContext _context;
        private readonly ProductServices _productServices;
        /*private readonly ImageServices _imageServices;*/
        public int pageSize = 2;

        public TSpsController(QLBanDTContext context, ProductServices productServices)
        {
            _context = context;
            _productServices = productServices;
            /*_imageServices = imageServices;*/
        }

        // GET: TSps
        public async Task<IActionResult> Index(int productPage = 1)
        {
            ViewBag.TotalProduct = await _productServices.GetTotalProductAsync();
            ViewBag.TotalMoney = await _productServices.GetTotalMoneyAsync();
            ViewBag.Revenue = await _productServices.GetRevenueAsync();
            ViewBag.Profit = await _productServices.GetProfitAsync();
            ViewBag.ProductSold = await _productServices.GetProductSoldAsync();

            var MaSp = await _productServices.GetTopProductsAsync();
            var TenSp = await _context.TSp.Where(x => x.MaSp == MaSp.ToString()).Select(x => x.TenSp).FirstOrDefaultAsync();

            var money = await _productServices.GetMoneyofTopProductsAsync();

            if (MaSp == null)
            {
                ViewBag.TopProduct = "Không có sản phẩm nào";
                ViewBag.TotalSales = "$0";
            }
            else
            {
                ViewBag.TopProduct = TenSp;
                ViewBag.TotalSales = money;
            }
            /*ar products = _context.TSp.Include(t => t.MaHangNavigation).Include(t => t.MaTlNavigation).ToList();
            return View(products);*/
            /* hàm skip bỏ qua số trang = số trang hiện tại * số lượng item trên mỗi trang
             * hàm take để lấy ra trang tiếp theo với số lượng bản ghi = pagesize*/
            return View(
                new ProductListViewModel
                {
                    Products = _context.TSp.Include(t => t.MaHangNavigation).Include(t => t.MaTlNavigation)
                    .Skip((productPage - 1) * pageSize).Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        itemsPerPage = pageSize,
                        currentPage = productPage,
                        totalItem = _context.TSp.Count(),
                    }
                }
            );

        }
        [HttpPost]
        public async Task<IActionResult> Search(string keyword, int productPage = 1)
        {
            return View(
                new SearchProductListViewModel
                {
                    Products = _context.TSp.Include(t => t.MaHangNavigation).Include(t => t.MaTlNavigation)
                    .Where(t => t.TenSp.Contains(keyword) || t.MaSp.Contains(keyword)
                    || t.MaHangNavigation.TenHang.Contains(keyword) || t.MaTlNavigation.TenTl.Contains(keyword))
                    .Skip((productPage - 1) * pageSize).Take(pageSize),
                    SearchPagingInfo = new SearchPagingInfo
                    {
                        itemsPerPage = pageSize,
                        currentPage = productPage,
                        totalItem = _context.TSp.Count(),
                        keyWord = keyword,
                        
                    }
                }
            );

        }
        public async Task<IActionResult> Total()
        {


            ViewBag.TotalProduct = await _productServices.GetTotalProductAsync();
            ViewBag.TotalMoney = await _productServices.GetTotalMoneyAsync();
            ViewBag.Revenue = await _productServices.GetRevenueAsync();
            ViewBag.Profit = await _productServices.GetProfitAsync();

            var MaSp = await _productServices.GetTopProductsAsync();
            var TenSp = await _context.TSp.Where(x => x.MaSp == MaSp.ToString()).Select(x => x.TenSp).FirstOrDefaultAsync();
            
            var money = await _productServices.GetMoneyofTopProductsAsync();

            if (MaSp == null)
            {
                ViewBag.TopProduct = "Không có sản phẩm nào";
                ViewBag.TotalSales = "$0";
            }
            else
            {
                ViewBag.TopProduct = TenSp;
                ViewBag.TotalSales = money;
            }


            return View();
        }

        // GET: TSps/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.TSp == null)
            {
                return NotFound();
            }

            var tSp = await _context.TSp
                .Include(t => t.MaHangNavigation)
                .Include(t => t.MaTlNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (tSp == null)
            {
                return NotFound();
            }
            ViewData["MaHang"] = new SelectList(_context.THangs, "MaHang", "TenHang");
            ViewData["MaTl"] = new SelectList(_context.TTheLoais, "MaTl", "TenTl");
            return View(tSp);
        }

        // GET: TSps/Create
        public async Task<IActionResult> Create()
        {
            /*var MaTl = (from tSp in _context.TSp
                        join tTl in _context.TTheLoais on tSp.MaTl equals tTl.MaTl
                        select new { tTl.MaTl, tTl.TenTl });*/
            var query = from c in _context.THoaDonNhaps
                        join c1 in _context.TChiTietHdns on c.SoHdn equals c1.SoHdn
                        select new
                        {
                            sohdn = c.SoHdn,
                            masp = c1.MaSp
                        };
            ViewData["MaSp"] = new SelectList(query.Select(t => t.masp).ToList());
            ViewData["MaHang"] = new SelectList(_context.THangs, "MaHang", "TenHang");
            ViewData["MaTl"] = new SelectList(_context.TTheLoais, "MaTl", "TenTl");

            return View();
        }

        // POST: TSps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSp,TenSp,MaTl,MaHang,DonGiaNhap,DonGiaBan,SoLuong,Anh")] TSp tSp/*, InputProducts inputProducts*/)
        {
            /*var fileName = await _imageServices.SaveFileAsync(inputProducts.Anh);
            tSp.Anh = fileName;*/
            if (ModelState.IsValid)
            {

                var product = _productServices.CreateProductAsync(tSp, tSp.MaSp);
                return RedirectToAction(nameof(Index));

            }
            var query = from c in _context.THoaDonNhaps
                        join c1 in _context.TChiTietHdns on c.SoHdn equals c1.SoHdn
                        select new
                        {
                            sohdb = c.SoHdn,
                            masp = c1.MaSp
                        };
            ViewData["MaSp"] = new SelectList(query.Select(t => t.masp).ToList());
            ViewData["MaHang"] = new SelectList(_context.THangs, "MaHang", "TenHang", tSp.MaHang);
            ViewData["MaTl"] = new SelectList(_context.TTheLoais, "MaTL", "TenTl", tSp.MaTl);
            return View(tSp);
        }
        /*public async Task<IActionResult> PostProduct([FromForm]InputProducts inputProducts)
        {
            var product = await _productServices.CreateProductAsync(inputProducts);
            return CreatedAtAction(nameof(Create), new { id = product.MaSp } , product);
        }
*/
        // GET: TSps/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.TSp == null)
            {
                return NotFound();
            }

            var tSp = await _context.TSp.FindAsync(id);
            if (tSp == null)
            {
                return NotFound();
            }
            ViewData["MaHang"] = new SelectList(_context.THangs, "MaHang", "TenHang", tSp.MaHang);
            ViewData["MaTl"] = new SelectList(_context.TTheLoais, "MaTl", "TenTl", tSp.MaTl);
            return View(tSp);
        }

        // POST: TSps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaSp,TenSp,MaTl,MaHang,DonGiaNhap,DonGiaBan,SoLuong,Anh")] TSp tSp)
        {
            if (id != tSp.MaSp)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tSp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TSpExists(tSp.MaSp))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaHang"] = new SelectList(_context.THangs, "MaHang", "TenHang", tSp.MaHang);
            ViewData["MaTl"] = new SelectList(_context.TTheLoais, "MaTl", "TenTl", tSp.MaTl);
            return View(tSp);
        }

        // GET: TSps/Delete/5

Views/Shared/LeftMenu.cshtml
<div class="app-sidebar-wrapper">
    <div class="app-sidebar sidebar-shadow">
        <div class="app-header__logo">
            <a href="#" data-toggle="tooltip" data-placement="bottom" title="" class="logo-src"></a>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
        <div class="scrollbar-sidebar scrollbar-container">
            <div class="app-sidebar__inner">
                <ul class="vertical-nav-menu">
                    <li class="app-sidebar__heading">Quản lí sản phẩm</li>
                    <li class="mm-active">
                        
                        <ul class="mm-show">
                            @* class="mm-active" *@
                            <li><a href="@Url.Action("Index", "TSps")">Sản phẩm</a></li>
                            <li><a href="@Url.Action("Total", "TSps")">Thống kê</a></li>
                            <li><a href="@Url.Action("Index", "THoaDonNhaps")">Hóa đơn nhập</a></li>
                            <li><a href="@Url.Action("Index", "THoaDonBans")">Hóa đơn xuất</a></li>
                            <li><a href="@Url.Action("Index","THangs")">Danh mục hãng</a></li>

                            @*
                            <li><a href="helpdesk-dashboard.html">Helpdesk</a></li>
                            <li><a href="monitoring-dashboard.html">Monitoring</a></li>
                            <li><a href="crypto-dashboard.html">Cryptocurrency</a></li>
                            <li><a href="pm-dashboard.html">Project Management</a></li>
                            <li><a href="statistics-dashboard.html">Statistics</a></li> *@
                        </ul>
                    </li>
                    <li class="app-sidebar__heading">Quản lí tài khoản</li>
                    <li class="mm-active">

                        <ul class="mm-show">
                            <li><a href="@Url.Action("Index","TKhachHangs")">Danh mục khách hàng</a></li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Views/Shared/MyLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Products Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="This is an example dashboard created using build-in elements and components.">
    <link rel="icon" href="favicon.ico">
    
    <meta name="msapplication-tap-highlight" content="no">
    <link href="~/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="app-container app-theme-gray">
        <div class="app-main">
            @* <div class="app-sidebar-wrapper"> *@
                @* Begin LeftMenu *@
                <partial name="LeftMenu" />
                @*End LeftMenu*@
            @* </div> *@
            <div class="app-sidebar-overlay d-none animated fadeIn"></div>
            <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="header-mobile-wrapper">
                        <div class="app-header__logo">
                            <a href="#" class="logo-src"></a>
                            <button type="button" class="hamburger hamburger--elastic mobile-toggle-sidebar-nav">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                            <div class="app-header__menu">
                                <span>
                                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                        <span class="btn-icon-wrapper">
                                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                                        </span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                    @* <div class="app-header"> *@
                        @* Begin App-Header*@
                        <partial name="AppHeader" />
                        @*End App-Header*@
                    @* </div> *@
                    <div class="app-inner-layout app-inner-layout-page">
                        @* <div class="app-inner-bar"> *@
                            @*Begin App-Inner-Bar*@
                            @*End App-Inner-Bar*@
                        @* </div> *@
                        @* <div class="app-inner-layout__wrapper"> *@
                            @*Main*@
                        <div class="app-inner-layout__wrapper">
                           
                            <div class="app-inner-layout__content">
                                <div class="tab-content">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>
                        @* </div> *@
                        </div>
                </div>
                @* <div class="app-wrapper-footer"> *@
                    <partial name="Footer" />
                @* </div> *@
                </div>
        </div>
        
    </div>
    <script src="~/js/script.js"></script>
<<<<<<< HEAD
    @RenderSection("Paginate", required: false)
=======
    @RenderSection("Scripts", required: false)
    @RenderSection("Pagination", required: false)
    @RenderSection("PaginateSearch", required: false)
>>>>>>> bc875c96f66c76dff785ed1380281fb5df082a71
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Admin.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>