Models/TChiTietHdn.cs
using System;
using System.Collections.Generic;

namespace Admin.Models
{
    public partial class TChiTietHdn
    {
        
        public string SoHdn { get; set; } = null!;
        public string MaSp { get; set; } = null!;
        public int? Slnhap { get; set; }
        public string? KhuyenMai { get; set; }

        public virtual TSp MaSpNavigation { get; set; } = null!;
        public virtual THoaDonNhap SoHdnNavigation { get; set; } = null!;
    }
}

Controllers/TChiTietHdnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Models;
using Admin.Services;

namespace Admin.Controllers
{
    public class TChiTietHdnsController : Controller
    {
        private readonly QLBanDTContext _context;
        private readonly InvoiceServices _invoiceServices;

        public TChiTietHdnsController(QLBanDTContext context)
        {
            _context = context;
        }

        // GET: TChiTietHdns
        public async Task<IActionResult> Index()
        {
            ViewBag.TT = 0;
            var qLBanDTContext = _context.TChiTietHdns.Include(t => t.MaSpNavigation)
                .Include(t => t.SoHdnNavigation)
                .Include(t => t.SoHdnNavigation.MaNccNavigation).Where(t => t.SoHdn == id);

            foreach (var item in qLBanDTContext)
            {
                ViewBag.TT += item.MaSpNavigation.DonGiaNhap * item.Slnhap;
            }

            _context.SaveChanges();
            return View(await qLBanDTContext.ToListAsync());
        }

        // GET: TChiTietHdns/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.TChiTietHdns == null)
            {
                return NotFound();
            }

            var tChiTietHdn = await _context.TChiTietHdns
                .Include(t => t.MaSpNavigation)
                .Include(t => t.SoHdnNavigation)
                .FirstOrDefaultAsync(m => m.SoHdn == id);
            if (tChiTietHdn == null)
            {
                return NotFound();
            }

            return View(tChiTietHdn);
        }

        // GET: TChiTietHdns/Create
        public IActionResult Create()
        {
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp");
            ViewData["SoHdn"] = new SelectList(_context.THoaDonNhaps, "SoHdn", "SoHdn");
            return View();
        }

        // POST: TChiTietHdns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SoHdn,MaSp,Slnhap,KhuyenMai")] TChiTietHdn tChiTietHdn)
        {
            /*if (ModelState.IsValid)
            {
                _context.Add(tChiTietHdn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "TenSp", tChiTietHdn.MaSp);
            ViewData["SoHdn"] = new SelectList(_context.THoaDonNhaps, "SoHdn", "SoHdn", tChiTietHdn.SoHdn);


            return View("Index", tChiTietHdn);*/

            /*if (ModelState.IsValid)
            {
                _context.Add(tChiTietHdn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp", tChiTietHdn.MaSp);
            ViewData["SoHdn"] = new SelectList(_context.THoaDonNhaps, "SoHdn", "SoHdn", tChiTietHdn.SoHdn);

            // Load a list of TChiTietHdn to display in the view
            
            return RedirectToAction("Index", new {id = tChiTietHdn.SoHdn});*/

            if (ModelState.IsValid)
            {
                var Hdn = _invoiceServices.createInvoiceIn(tChiTietHdn,tChiTietHdn.MaSp);

                return RedirectToAction(nameof(Index));
            }

            ViewData["SoHdn"] = new SelectList(_context.THoaDonNhaps, "SoHdn", "SoHdn", tChiTietHdn.SoHdn);
            return RedirectToAction("Index", new { id = tChiTietHdn.SoHdn });
        }

        // GET: TChiTietHdns/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.TChiTietHdns == null)
            {
                return NotFound();
            }

            var tChiTietHdn = await _context.TChiTietHdns.FindAsync(id);
            if (tChiTietHdn == null)
            {
                return NotFound();
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp", tChiTietHdn.MaSp);
            ViewData["SoHdn"] = new SelectList(_context.THoaDonNhaps, "SoHdn", "SoHdn", tChiTietHdn.SoHdn);
            return View(tChiTietHdn);
        }

        // POST: TChiTietHdns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SoHdn,MaSp,Slnhap,KhuyenMai")] TChiTietHdn tChiTietHdn)
        {
            if (id != tChiTietHdn.SoHdn)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tChiTietHdn);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TChiTietHdnExists(tChiTietHdn.SoHdn))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp", tChiTietHdn.MaSp);
            ViewData["SoHdn"] = new SelectList(_context.THoaDonNhaps, "SoHdn", "SoHdn", tChiTietHdn.SoHdn);
            return View(tChiTietHdn);
        }

        // GET: TChiTietHdns/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.TChiTietHdns == null)
            {
                return NotFound();
            }

            var tChiTietHdn = await _context.TChiTietHdns
                .Include(t => t.MaSpNavigation)
                .Include(t => t.SoHdnNavigation)
                .FirstOrDefaultAsync(m => m.SoHdn == id);
            if (tChiTietHdn == null)
            {
                return NotFound();
            }

            return View(tChiTietHdn);
        }

        // POST: TChiTietHdns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.TChiTietHdns == null)
            {
                return Problem("Entity set 'QLBanDTContext.TChiTietHdns'  is null.");
            }
            var tChiTietHdn = await _context.TChiTietHdns.FindAsync(id);
            if (tChiTietHdn != null)
            {
                _context.TChiTietHdns.Remove(tChiTietHdn);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TChiTietHdnExists(string id)
        {
          return (_context.TChiTietHdns?.Any(e => e.SoHdn == id)).GetValueOrDefault();
        }
    }
}

Views/TChiTietHdns/Create.cshtml
@model Admin.Models.TChiTietHdn

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h1>Create</h1>

<h4>TChiTietHdn</h4>
<hr />
<form asp-action="Create">
    <div class="row">
        
            <div class="col-md-12">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="SoHdn" class="control-label">Số hóa đơn</label>
                    <select asp-for="SoHdn" class="form-control" asp-items="ViewBag.SoHDN"></select>
                </div>
                <div class="form-group">
                    <label asp-for="MaSp" class="control-label">Sản phẩm</label>
                    <input asp-for="MaSp" class="form-control" />
                    <span asp-validation-for="MaSp" class="text-danger"></span>
                </div>


            </div>
<<<<<<< HEAD
            <div class="form-group">
                <label asp-for="Slnhap" class="control-label"></label>
                <input asp-for="Slnhap" class="form-control" />
                <span asp-validation-for="Slnhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KhuyenMai" class="control-label"></label>
                <input asp-for="KhuyenMai" class="form-control" />
                <span asp-validation-for="KhuyenMai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>

    @Html.ActionLink("Quay lại", "Index", "TChiTietHdns", new { id = ViewBag.HDN})
</div>

Views/TChiTietHdns/Delete.cshtml
@model Admin.Models.TChiTietHdn

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TChiTietHdn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slnhap)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slnhap)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhuyenMai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhuyenMai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaSpNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaSpNavigation.MaSp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoHdnNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoHdnNavigation.SoHdn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SoHdn" />
        <input type="hidden" asp-for="MaSp" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/TChiTietHdns/Details.cshtml
@model Admin.Models.TChiTietHdn

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TChiTietHdn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slnhap)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slnhap)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhuyenMai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhuyenMai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaSpNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaSpNavigation.MaSp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoHdnNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoHdnNavigation.SoHdn)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/TChiTietHdns/Edit.cshtml
@model Admin.Models.TChiTietHdn

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h1>Edit</h1>

<h4>TChiTietHdn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SoHdn" />
            <input type="hidden" asp-for="MaSp" />
            <div class="form-group">
                <label asp-for="Slnhap" class="control-label"></label>
                <input asp-for="Slnhap" class="form-control" />
                <span asp-validation-for="Slnhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KhuyenMai" class="control-label"></label>
                <input asp-for="KhuyenMai" class="form-control" />
                <span asp-validation-for="KhuyenMai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/TChiTietHdns/Index.cshtml
@model IEnumerable<Admin.Models.TChiTietHdn>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Slnhap)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KhuyenMai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaSpNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoHdnNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Slnhap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhuyenMai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaSpNavigation.MaSp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoHdnNavigation.SoHdn)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>