Models/THoaDonBan.cs
using System;
using System.Collections.Generic;

namespace Admin.Models
{
    public partial class THoaDonBan
    {
        public THoaDonBan()
        {
            TChiTietHdbs = new HashSet<TChiTietHdb>();
        }

        public string SoHdb { get; set; } = null!;
        public DateTime? NgayBan { get; set; }
        public string? MaNguoiDung { get; set; }
        public decimal? TongHdb { get; set; }

        public virtual Nguoidung? MaKhNavigation { get; set; }
        public virtual ICollection<TChiTietHdb> TChiTietHdbs { get; set; }

    }
}

Controllers/TChiTietHdbsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Models;

namespace Admin.Controllers
{
    public class TChiTietHdbsController : Controller
    {
        private readonly QLBanDTContext _context;

        public TChiTietHdbsController(QLBanDTContext context)
        {
            _context = context;
        }

        // GET: TChiTietHdbs
        public async Task<IActionResult> Index(string id)
        {
            var qLBanDTContext = _context.TChiTietHdbs.Where(t => t.SoHdb == id)
                .Include(t => t.MaSpNavigation).Include(t => t.SoHdbNavigation)
                .Include(t => t.SoHdbNavigation.MaKhNavigation);
            return View(await qLBanDTContext.ToListAsync());
        }

        // GET: TChiTietHdbs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.TChiTietHdbs == null)
            {
                return NotFound();
            }

            var tChiTietHdb = await _context.TChiTietHdbs
                .Include(t => t.MaSpNavigation)
                .Include(t => t.SoHdbNavigation)
                .FirstOrDefaultAsync(m => m.SoHdb == id);
            if (tChiTietHdb == null)
            {
                return NotFound();
            }

            return View(tChiTietHdb);
        }

        // GET: TChiTietHdbs/Create
        public IActionResult Create()
        {
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp");
            ViewData["SoHdb"] = new SelectList(_context.THoaDonBans, "SoHdb", "SoHdb");
            return View();
        }

        // POST: TChiTietHdbs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SoHdb,MaSp,Slban,KhuyenMai")] TChiTietHdb tChiTietHdb)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tChiTietHdb);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp", tChiTietHdb.MaSp);
            ViewData["SoHdb"] = new SelectList(_context.THoaDonBans, "SoHdb", "SoHdb", tChiTietHdb.SoHdb);
            return View(tChiTietHdb);
        }

        // GET: TChiTietHdbs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.TChiTietHdbs == null)
            {
                return NotFound();
            }

            var tChiTietHdb = await _context.TChiTietHdbs.FindAsync(id);
            if (tChiTietHdb == null)
            {
                return NotFound();
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp", tChiTietHdb.MaSp);
            ViewData["SoHdb"] = new SelectList(_context.THoaDonBans, "SoHdb", "SoHdb", tChiTietHdb.SoHdb);
            return View(tChiTietHdb);
        }

        // POST: TChiTietHdbs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SoHdb,MaSp,Slban,KhuyenMai")] TChiTietHdb tChiTietHdb)
        {
            if (id != tChiTietHdb.SoHdb)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tChiTietHdb);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TChiTietHdbExists(tChiTietHdb.SoHdb))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.TSp, "MaSp", "MaSp", tChiTietHdb.MaSp);
            ViewData["SoHdb"] = new SelectList(_context.THoaDonBans, "SoHdb", "SoHdb", tChiTietHdb.SoHdb);
            return View(tChiTietHdb);
        }

        // GET: TChiTietHdbs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.TChiTietHdbs == null)
            {
                return NotFound();
            }

            var tChiTietHdb = await _context.TChiTietHdbs
                .Include(t => t.MaSpNavigation)
                .Include(t => t.SoHdbNavigation)
                .FirstOrDefaultAsync(m => m.SoHdb == id);
            if (tChiTietHdb == null)
            {
                return NotFound();
            }

            return View(tChiTietHdb);
        }

        // POST: TChiTietHdbs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.TChiTietHdbs == null)
            {
                return Problem("Entity set 'QLBanDTContext.TChiTietHdbs'  is null.");
            }
            var tChiTietHdb = await _context.TChiTietHdbs.FindAsync(id);
            if (tChiTietHdb != null)
            {
                _context.TChiTietHdbs.Remove(tChiTietHdb);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TChiTietHdbExists(string id)
        {
          return (_context.TChiTietHdbs?.Any(e => e.SoHdb == id)).GetValueOrDefault();
        }
    }
}

Controllers/THoaDonBansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Models;
using Admin.Models.ViewModels;
using System.Drawing.Printing;
using Admin.Services;
using System.Net.NetworkInformation;


namespace Admin.Controllers
{
    public class THoaDonBansController : Controller
    {
        private readonly QLBanDTContext _context;
        private readonly ProductServices _productServices;
        public int pageSize = 10;

        public THoaDonBansController(QLBanDTContext context)
        {
            _context = context;
        }

        // GET: THoaDonBans
        [Route("HDB/List")]
        public async Task<IActionResult> Index(int invoiceOutPage = 1)
        {
            /*var qLBanDTContext = _context.THoaDonBans.Include(t => t.MaKhNavigation);
            return View(await qLBanDTContext.ToListAsync());*/

            return View(
                new InvoiceOutListViewModel
                {
                    InvoiceOut = _context.TChiTietHdbs.Include(t => t.SoHdbNavigation).Include(t => t.SoHdbNavigation.MaKhNavigation)
                    .Skip((invoiceOutPage - 1) * pageSize).Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        itemsPerPage = pageSize,
                        currentPage = invoiceOutPage,
                        totalItem = _context.TChiTietHdbs.Count()
                    }
                }
            ); ;

        }

        // GET: THoaDonBans/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.THoaDonBans == null)
            {
                return NotFound();
            }

            var tHoaDonBan = await _context.THoaDonBans
                .Include(t => t.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.SoHdb == id);
            if (tHoaDonBan == null)
            {
                return NotFound();
            }

            return View(tHoaDonBan);
        }

        // GET: THoaDonBans/Create
        public IActionResult Create()
        {
            ViewData["MaKh"] = new SelectList(_context.TKhachHangs, "MaKh", "MaKh");
            return View();
        }

        // POST: THoaDonBans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SoHdb,NgayBan,MaKh,TongHdb,")] THoaDonBan tHoaDonBan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tHoaDonBan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.TKhachHangs, "MaKh", "MaKh", tHoaDonBan.MaNguoiDung);
            return View(tHoaDonBan);
        }

        // GET: THoaDonBans/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.THoaDonBans == null)
            {
                return NotFound();
            }

            var tHoaDonBan = await _context.THoaDonBans.FindAsync(id);
            if (tHoaDonBan == null)
            {
                return NotFound();
            }
            ViewData["MaKh"] = new SelectList(_context.TKhachHangs, "MaKh", "MaKh", tHoaDonBan.MaNguoiDung);
            return View(tHoaDonBan);
        }

        // POST: THoaDonBans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SoHdb,NgayBan,MaKh,TongHdb")] THoaDonBan tHoaDonBan)
        {
            if (id != tHoaDonBan.SoHdb)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tHoaDonBan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!THoaDonBanExists(tHoaDonBan.SoHdb))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.TKhachHangs, "MaKh", "MaKh", tHoaDonBan.MaNguoiDung);
            return View(tHoaDonBan);
        }

        // GET: THoaDonBans/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.THoaDonBans == null)
            {
                return NotFound();
            }

            var tHoaDonBan = await _context.THoaDonBans
                .Include(t => t.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.SoHdb == id);
            if (tHoaDonBan == null)
            {
                return NotFound();
            }

            return View(tHoaDonBan);
        }

        // POST: THoaDonBans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.THoaDonBans == null)
            {
                return Problem("Entity set 'QLBanDTContext.THoaDonBans'  is null.");
            }
            var tHoaDonBan = await _context.THoaDonBans.FindAsync(id);
            if (tHoaDonBan != null)
            {
                _context.THoaDonBans.Remove(tHoaDonBan);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool THoaDonBanExists(string id)
        {
          return (_context.THoaDonBans?.Any(e => e.SoHdb == id)).GetValueOrDefault();
        }
    }
}

Views/THoaDonBans/Create.cshtml
@model Admin.Models.THoaDonBan

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h1>Create</h1>

<h4>THoaDonBan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SoHdb" class="control-label">Số hóa đơn</label>
                <input asp-for="SoHdb" class="form-control" />
                <span asp-validation-for="SoHdb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayBan" class="control-label">Ngày bán</label>
                <input asp-for="NgayBan" class="form-control" />
                <span asp-validation-for="NgayBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaKh" class="control-label">Khách hàng</label>
                <select asp-for="MaKh" class ="form-control" asp-items="ViewBag.MaKh"></select>
            </div>
            <div class="form-group">
                <label asp-for="TongHdb" class="control-label"></label>
                <input asp-for="TongHdb" class="form-control" />
                <span asp-validation-for="TongHdb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/THoaDonBans/Delete.cshtml
@model Admin.Models.THoaDonBan

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>THoaDonBan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayBan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongHdb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongHdb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaKhNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaKhNavigation.MaKh)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SoHdb" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/THoaDonBans/Details.cshtml
@model Admin.Models.THoaDonBan

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>THoaDonBan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayBan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongHdb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongHdb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaKhNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaKhNavigation.MaKh)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.SoHdb">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/THoaDonBans/Edit.cshtml
@model Admin.Models.THoaDonBan

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>THoaDonBan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SoHdb" />
            <div class="form-group">
                <label asp-for="NgayBan" class="control-label"></label>
                <input asp-for="NgayBan" class="form-control" />
                <span asp-validation-for="NgayBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaKh" class="control-label"></label>
                <select asp-for="MaKh" class="form-control" asp-items="ViewBag.MaKh"></select>
                <span asp-validation-for="MaKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TongHdb" class="control-label"></label>
                <input asp-for="TongHdb" class="form-control" />
                <span asp-validation-for="TongHdb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/THoaDonBans/Index.cshtml
@* @model IEnumerable<Admin.Models.THoaDonBan> *@
@using Admin.Models.ViewModels;
@model InvoiceOutListViewModel;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<div class="backgr-color" style="background-color: white; padding-top: 10px; border-radius: 5px; box-shadow: 0 2px 10px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.1);">
    <div>
        <h1 class="invoiceOut-list">DANH SÁCH HÓA ĐƠN BÁN</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Mã đơn hàng
                    </th>
                    <th>
                        Ngày bán
                    </th>
                    <th>
                        Khách hàng
                    </th>
                    <th>
                        Tổng tiền
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.InvoiceOut)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoHdb)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoHdbNavigation.NgayBan)
                        </td>
                        <td>
<<<<<<< HEAD
                            @Html.DisplayFor(modelItem => item.SoHdbNavigation.MaKhNavigation)
=======
                            @Html.DisplayFor(modelItem => item.SoHdbNavigation.MaKhNavigation.Hoten)
>>>>>>> bc875c96f66c76dff785ed1380281fb5df082a71
                        </td>
                        @* <td>
                    @Html.DisplayFor(modelItem => item.Slban)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.KhuyenMai)
                    </td> *@
                        <td>
                            @Html.DisplayFor(modelItem => item.SoHdbNavigation.TongHdb)
                        </td>


                        <td>

                            @Html.ActionLink("Chi tiết","Index", "TChiTietHdbs", new { id = item.SoHdb})
                            
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
       

         <ul class="pagination justify-content-end" style="float: right; width: 50%; margin-right: 15px;">
            <li class="page-item"><a class="page-link" href="~/ThoaDonBans/?productPage=productPage-1">Previous</a></li>

            @for (int i = 1; i <= Model.PagingInfo.totalPage; i++)
            {
                <li class="page-item"><a class="page-link" href="~/TSps/?productPage=@i">@i</a></li>
            }

            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </div>
</div>

@section Paginate{
    <script>
        function loadPage(page, pageSize){
            $.ajax({
                URL: '/THoaDonBanController/Index',
                data: {page: page, pageSize: pageSize },
                success: function (data) {
                    $('content').html(data);
                },
                error: function () {
                    alert('Có lõi xảy ra khi tải trang.')
                }
            })
        }
    </script>
}


<style>
    .btn {
        float: left;
        margin-left: 15px;
    }

    .invoiceOut-list {
        margin-top: revert-layer;
        text-align: center;
        font-size: 2rem;
    }
</style>